global class HIFulfillmentErrorEditingSelectionJSON {
	public Long selection_id; //51928
	public Integer state_carrier_id; //212
	public String error_type; //Categories::AssignedCategoryValidator::EmployeesMissingAssignedCategory
	public String error_message; //Employee class must be set for: 7757869432536783
	public Long employee_id; //7757869432536783
	public Long company_id; //7757616923717082
	public String type; //NHE
	public String selection_uuid;
	public String benefit_type;
}