/**
 * @name         HIGroupQualificationAutomationJSON
 * @author       Bhagat Singh
 * @date         03 June 2021
 * @description  JSON structure for HIGroupEvent.Event_Info for group_qualification_automation events
 * @test classes HIGroupQualificationAutomationStatusTest
 * @revisions    Date ------------ Name ------------ Comments
 **/
public class HIGroupQualificationAutomationJSON {
	public String event_id;
	public String company_id;
	public String application_id;
	public String application_type;
	public String qualification_automation_status;
	public String qualification_automation_message;
	public String event_type;
}