/**
 * @name         HIGroupEventOAIntroEmailJSON
 * @author       Bhagat Singh
 * @date         03 June 2021
 * @description  JSON structure for HIGroupEvent.Event_Info for OA_intro_email events
 * @test classes HIGroupEventOAIntroEmailTest
 * @revisions    Date ------------ Name ------------ Comments
 **/
public class HIGroupEventOAIntroEmailJSON {
	public String event_id;
	public String company_id;
	public String application_id;
	public String application_type;
	public String email_body;
	public String event_type;
}