/**
* @name         SubmissionAutomationJSON
* @author       Neha Dabas
* @date         01-22-2021
* @description  JSON structure for HIGroupEvent.Event_Info for group_submission_automation events
* @test classes HIGroupEventTriggerHelperTest
* @revisions    Date ------------ Name ------------ Comments
**/
public class SubmissionAutomationJSON {
	public String event_id;
    public String company_id;
    public String application_type;
    public String event_type;
    public String application_id;
    public String state_carrier_id;
    public String error_message;
    public String automation_status;
    public String automation_message;
    public String hippo_link;
}